[general]
format=wav|gsm
maxmsg=50
maxsecs=180
minsecs=3



[office-default]
1000 => 1234,Sales Team
1001 => 1234,Support Team
1002 => 1234,Admin Team
1003 => 1234,Manager VM


root@saad2-VirtualBox:/etc/asterisk# cat extensions.conf
[general]
static=yes
writeprotect=no


[office-incoming]
exten => _9XX,1,NoOp(--- Call inside Company ---)
same => n,Answer()
same => n,GotoIfTime(09:00-18:00,mon-fri,*,*?business-hours,s,1)
same => n,Goto(after-hours,s,1)


[business-hours]
exten => s,1,NoOp(--- Business Hours Welcome Menu ---)
same => n,Background(welcome)
same => n,Background(menu-option)
same => n,WaitExten(5)

# If customer press 1
exten => 1,1,NoOp(--- Sales Selected ---)
same => n,Playback(sales)
same => n,Dial(SIP/101,30)
same => n,Goto(sales-check-${DIALSTATUS},1)

# Sales voicemail status blocks
exten => sales-check-BUSY,1,VoiceMail(1000@office-default,b)
same => n,Hangup()
exten => sales-check-NOANSWER,1,VoiceMail(1000@office-default,u)
same => n,Hangup()
exten => _sales-check-.,1,VoiceMail(1000@office-default,u)

# if CUSTOMER press 2 (Support Department):
exten => 2,1,NoOp(--- Support Selected ---)
same => n,Playback(support)
same => n,Dial(SIP/102,30)
same => n,Goto(support-check-${DIALSTATUS},1)

exten => support-check-BUSY,1,VoiceMail(1001@office-default,b)
same => n,Hangup()
exten => support-check-NOANSWER,1,VoiceMail(1001@office-default,u)
same => n,Hangup()
exten => _support-check-.,1,VoiceMail(1001@office-default,u)
same => n,Hangup()

# if CUSTOMER press 3 DABAYE (Admin Department):
exten => 3,1,NoOp(--- Admin Selected ---)
same => n,Playback(administration)
same => n,Dial(SIP/103,30)
same => n,Goto(admin-check-${DIALSTATUS},1)

exten => admin-check-BUSY,1,VoiceMail(1003@office-default,b)
same => n,Hangup()
exten => admin-check-NOANSWER,1,VoiceMail(1003@office-default,u)
same => n,Hangup()
exten => _admin-check-.,1,VoiceMail(1003@office-default,u)
same => n,Hangup()

exten => i,1,Playback(invalid-option)
same => n,Goto(s,1)
exten => t,1,Playback(goodbye)
same => n,Hangup()

[after-hours]
exten => s,1,NoOp(--- Office Closed Call ---)
same => n,Playback(after-hour)   # office is closed right now
same => n,VoiceMail(1000@office-default,u)
same => n,Hangup()

[office-internal]
exten => _1XX,1,NoOp(--- Internal Call ---)
same => n,Dial(SIP/${EXTEN},30)
same => n,Hangup()

# to check voicemail
exten => *97,1,NoOp(--- Check My Voicemail ---)
same => n,VoiceMailMain(${CALLERID(num)}@office-default)
same => n,Hangup()


[office-internal]
exten => 999,1,NoOp(----- Testing inbound -----)
same => n,Goto(office-incoming,s,1)
