[general]
context=office-incoming
udpbindaddr=0.0.0.0
transport=udp



[101]
type=friend
host=dynamic
secret=salesdept2026
context=office-internal
qualify=yes
nat=force_rport,comedia
callerid="sales agent" <101>


[102]
type=friend
host=dynamic
secret=supportdept2026
context=office-internal
qualify=yes
nat=force_rport,comedia
callerid="support agent" <102>



[103]
type=friend
host=dynamic
secret=admindept2026
context=office-internal
qualify=yes
nat=force_rport,comedia
callerid="admin Office" <103>

[201]
type=friend
host=dynamic
secret=manager2026
context=office-incoming
qualify=yes
nat=force_rport,comedia
callerid="Outside Manager" <201>
